name: Deploy Svachalan

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            cd ./svachalan

            git pull origin main

            docker compose down --remove-orphans

            docker compose -f docker-compose.prod.yml build --no-cache

            docker compose -f docker-compose.prod.yml up -d

            docker image prune -f

